%% SYNTAX TEST "Packages/mermaid/mermaid.sublime-syntax"

%% Example code
%% ^ punctuation.definition.comment.mermaid

graph TB %% tab completion: 'graph'
%% <- meta.declaration.graph.mermaid
%%  ^ keyword.type.main.mermaid
%%    ^ constant.type.graph.mermaid
%%       ^ punctuation.definition.comment.mermaid

  ID-1[This is the text in the box] %% tab completion: 'node'
%% <- meta.declaration.graph.node.mermaid
%%   ^ entity.name.node.mermaid
%%    ^ keyword.operator.node.begin.mermaid
%%     ^ string.text.node.mermaid
%%                                ^ keyword.operator.node.end.mermaid
%%                                  ^ punctuation.definition.comment.mermaid

  ID-2[This is the text in the box]
  ID-1---ID-2 %% tab completion: 'link'
%% ^ meta.declaration.graph.link.mermaid
%%            ^ punctuation.definition.comment.mermaid

  class ID-1 className %% tab completion: 'class'
%% <- meta.declaration.graph.styling.mermaid
%% ^ keyword.type.styling.mermaid
%%           ^ entity.name.class.styling.mermaid
%%                     ^ punctuation.definition.comment.mermaid

  click ID-1 "http://www.github.com" "Tooltip for a link" %% tab completion: 'click'
%% <- meta.declaration.graph.interaction.mermaid
%% ^ keyword.type.interaction.mermaid
%%           ^ punctuation.definition.string.begin.mermaid
%%            ^ string.quoted.double.mermaid
%%                                 ^ punctuation.definition.string.end.mermaid
%%                                   ^ punctuation.definition.string.begin.mermaid
%%                                    ^ string.quoted.double.mermaid
%%                                                      ^ punctuation.definition.string.end.mermaid
%%                                                        ^ punctuation.definition.comment.mermaid
  click ID-1 callback "Tooltip for a callback" %% tab completion: 'click'
%%           ^ entity.name.callback.interaction.mermaid

  subgraph This is the subgraph text
%% <- meta.declaration.subgraph.mermaid
%% ^ keyword.type.group.begin.mermaid
%%         ^ string.text.subgraph.mermaid
    ID-3[This is the text in the box]
    ID-2-->ID-3
  end %% tab completion: 'subgraph'
%% <- meta.declaration.subgraph.mermaid
%% ^ keyword.type.group.end.mermaid
%%    ^ punctuation.definition.comment.mermaid
