%% SYNTAX TEST "Packages/mermaid/mermaid.sublime-syntax"

%% Example code
%% ^ punctuation.definition.comment.mermaid

graph TB %% tab completion: 'graph'
%% <- meta.declaration.graph.mermaid
%%  ^ keyword.type.graph.mermaid
%%    ^ constant.type.graph.mermaid
%%       ^ punctuation.definition.comment.mermaid

  ID-1[This is the text in the box] %% tab completion: 'node'
%% <- meta.declaration.node.graph.mermaid
%%   ^ entity.name.node.graph.mermaid
%%    ^ keyword.operator.begin.node.graph.mermaid
%%     ^ string.text.node.graph.mermaid
%%                                ^ keyword.operator.end.node.graph.mermaid
%%                                  ^ punctuation.definition.comment.mermaid

  ID-2[This is the text in the box]
  ID-1---ID-2 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%    ^^^ keyword.operator.link.graph.mermaid
%%            ^ punctuation.definition.comment.mermaid
  ID-1---This is the link text---ID-2 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%    ^^^ keyword.operator.link.graph.mermaid
%%       ^ string.text.link.graph.mermaid
%%                            ^^^ keyword.operator.link.graph.mermaid
%%                                    ^ punctuation.definition.comment.mermaid
  ID-1-->|This is the link text|ID-2 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%    ^^^ keyword.operator.link.graph.mermaid
%%       ^ keyword.operator.begin.text.link.graph.mermaid
%%        ^ string.text.link.graph.mermaid
%%                             ^ keyword.operator.end.text.link.graph.mermaid
%%                                   ^ punctuation.definition.comment.mermaid
  ID-1 --- This is the link text --> ID-2 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%     ^^^ keyword.operator.link.graph.mermaid
%%         ^ string.text.link.graph.mermaid
%%                               ^^^ keyword.operator.link.graph.mermaid
%%                                        ^ punctuation.definition.comment.mermaid

  class ID-1 className %% tab completion: 'class'
%% <- meta.declaration.styling.graph.mermaid
%% ^ keyword.type.styling.graph.mermaid
%%           ^ entity.name.styling.graph.mermaid
%%                     ^ punctuation.definition.comment.mermaid

  click ID-1 "https://github.com" "Tooltip text" %% tab completion: 'click'
%% <- meta.declaration.interaction.graph.mermaid
%% ^ keyword.type.interaction.graph.mermaid
%%           ^ punctuation.definition.string.begin.mermaid
%%            ^ string.quoted.double.mermaid
%%                              ^ punctuation.definition.string.end.mermaid
%%                                ^ punctuation.definition.string.begin.mermaid
%%                                 ^ string.quoted.double.mermaid
%%                                             ^ punctuation.definition.string.end.mermaid
%%                                               ^ punctuation.definition.comment.mermaid
  click ID-1 callback "Tooltip for a callback" %% tab completion: 'click'
%%           ^ entity.name.callback.interaction.graph.mermaid

  subgraph This is the subgraph text
%% <- meta.declaration.sub.graph.mermaid
%% ^ keyword.type.begin.sub.graph.mermaid
%%         ^ string.text.sub.graph.mermaid
    ID-3[This is the text in the box]
    ID-2-->ID-3
%%  ^ meta.declaration.sub.graph.mermaid
%%      ^^^ keyword.operator.link.graph.mermaid
  end %% tab completion: 'subgraph'
%% <- meta.declaration.sub.graph.mermaid
%% ^ keyword.type.end.sub.graph.mermaid
%%    ^ punctuation.definition.comment.mermaid

sequenceDiagram %% tab completion: 'sequenceDiagram'
%% <- meta.declaration.diagram.mermaid
%% ^ keyword.type.diagram.mermaid
  participant Alice
%% ^ keyword.type.actor.diagram.mermaid
%% <- meta.declaration.actor.diagram.mermaid
%%            ^ entity.name.actor.diagram.mermaid
  participant Bob
  Alice->John: Hello John, how are you?
%% <- meta.declaration.message.diagram.mermaid
%%     ^^ keyword.operator.message.diagram.mermaid
%%           ^ keyword.operator.message.diagram.mermaid
%%             ^ string.text.message.diagram.mermaid
  loop Healthcheck
%% <- meta.declaration.loop.diagram.mermaid
%% ^ keyword.type.begin.loop.diagram.mermaid
%%     ^ string.text.loop.diagram.mermaid
      John->John: Fight against hypochondria
%% <- meta.declaration.message.diagram.mermaid
%%        ^^ keyword.operator.message.diagram.mermaid
%%              ^ keyword.operator.message.diagram.mermaid
%%                ^ string.text.message.diagram.mermaid
  end
%% <- meta.declaration.loop.diagram.mermaid
%% ^ keyword.type.end.loop.diagram.mermaid
  Note right of John: Rational thoughts <br/>prevail...
%% <- meta.declaration.note.diagram.mermaid
%% ^ keyword.type.note.diagram.mermaid
%%     ^ constant.type.note.diagram.mermaid
%%           ^ constant.type.note.diagram.mermaid
%%                  ^ keyword.operator.note.diagram.mermaid
%%                    ^ string.text.note.diagram.mermaid
  John-->Alice: Great!
  John->Bob: How about you?
  Bob-->John: Jolly good!
