%% SYNTAX TEST "Packages/mermaid/mermaid.sublime-syntax"

%% Example code
%% ^ punctuation.definition.comment.mermaid

graph TB %% tab completion: 'graph'
%% <- meta.declaration.graph.mermaid
%%  ^ keyword.type.graph.mermaid
%%    ^ constant.type.graph.mermaid
%%       ^ punctuation.definition.comment.mermaid
  ID-1[Node 1] %% tab completion: 'node'
%% <- meta.declaration.node.graph.mermaid
%%   ^ entity.name.node.graph.mermaid
%%    ^ keyword.operator.begin.node.graph.mermaid
%%     ^ string.text.node.graph.mermaid
%%           ^ keyword.operator.end.node.graph.mermaid
%%             ^ punctuation.definition.comment.mermaid
  ID-2>Node 2]
  ID-3(Node 3)
  ID-1---ID-2 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%    ^^^ keyword.operator.link.graph.mermaid
%%            ^ punctuation.definition.comment.mermaid
  ID-1 --> ID-3 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%     ^^^ keyword.operator.link.graph.mermaid
%%              ^ punctuation.definition.comment.mermaid
  ID-2--Link between 2 and 3---ID-3 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%    ^^ keyword.operator.link.graph.mermaid
%%      ^ string.text.link.graph.mermaid
%%                          ^^^ keyword.operator.link.graph.mermaid
%%                                  ^ punctuation.definition.comment.mermaid
  ID-1-->|Action from 1 to 3|ID-3 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%    ^^^ keyword.operator.link.graph.mermaid
%%       ^ keyword.operator.begin.text.link.graph.mermaid
%%        ^ string.text.link.graph.mermaid
%%                          ^ keyword.operator.end.text.link.graph.mermaid
%%                                ^ punctuation.definition.comment.mermaid
  ID-3 -- Action from 3 to 2 --> ID-2 %% tab completion: 'link'
%% ^ meta.declaration.link.graph.mermaid
%%     ^^ keyword.operator.link.graph.mermaid
%%        ^ string.text.link.graph.mermaid
%%                           ^^^ keyword.operator.link.graph.mermaid
%%                                    ^ punctuation.definition.comment.mermaid
  classDef blue fill:#08f,stroke:#fff %% tab completion: 'class'
%% <- meta.declaration.styling.graph.mermaid
%% ^ keyword.type.styling.graph.mermaid
%%         ^ entity.name.styling.graph.mermaid
%%              ^ string.text.styling.graph.mermaid
%%                                    ^ punctuation.definition.comment.mermaid
  class ID-1 blue %% tab completion: 'class'
%% <- meta.declaration.styling.graph.mermaid
%% ^ keyword.type.styling.graph.mermaid
%%           ^ support.name.styling.graph.mermaid
%%                ^ punctuation.definition.comment.mermaid
  click ID-1 "https://github.com" "Tooltip text" %% tab completion: 'click'
%% <- meta.declaration.interaction.graph.mermaid
%% ^ keyword.type.interaction.graph.mermaid
%%           ^ punctuation.definition.string.begin.mermaid
%%            ^ string.quoted.double.mermaid
%%                              ^ punctuation.definition.string.end.mermaid
%%                                ^ punctuation.definition.string.begin.mermaid
%%                                 ^ string.quoted.double.mermaid
%%                                             ^ punctuation.definition.string.end.mermaid
%%                                               ^ punctuation.definition.comment.mermaid
  click ID-1 alert "Tooltip for a callback" %% tab completion: 'click'
%%           ^ entity.name.callback.interaction.graph.mermaid
  subgraph A subgraph
%% <- meta.declaration.sub.graph.mermaid
%% ^ keyword.type.begin.sub.graph.mermaid
%%         ^ string.text.sub.graph.mermaid
    ID-4{Node 4}
    ID-5((fa:fa-spinner))
    ID-6["Node 6 (same #quot;shape#quot;)"]
    ID-4-.->ID-5
%%      ^^^^ keyword.operator.link.graph.mermaid
    ID-5 -. Action from 5 to 4 .-> ID-4
%%       ^^ keyword.operator.link.graph.mermaid
%%                             ^^^ keyword.operator.link.graph.mermaid
    ID-5==>ID-6
%%      ^^^ keyword.operator.link.graph.mermaid
    ID-6 == Action from 6 to 5 ==> ID-5
%%       ^^ keyword.operator.link.graph.mermaid
%%                             ^^^ keyword.operator.link.graph.mermaid
%%  ^ meta.declaration.sub.graph.mermaid
  end %% tab completion: 'subgraph'
%% <- meta.declaration.sub.graph.mermaid
%% ^ keyword.type.end.sub.graph.mermaid
%%    ^ punctuation.definition.comment.mermaid

sequenceDiagram
%% <- meta.declaration.diagram.mermaid
%% ^ keyword.type.diagram.mermaid
  participant A as Alice
%% <- meta.declaration.actor.diagram.mermaid
%% ^ keyword.type.actor.diagram.mermaid
%%            ^ entity.name.actor.diagram.mermaid
%%              ^^ keyword.operator.alias.actor.diagram.mermaid
%%                 ^ string.text.alias.actor.diagram.mermaid
  participant B as Bob
  participant C as Carol
  Note left of A: Alice likes to chat
%% <- meta.declaration.note.diagram.mermaid
%% ^ keyword.type.note.diagram.mermaid
%%     ^ constant.type.note.diagram.mermaid
%%          ^ constant.type.note.diagram.mermaid
%%              ^ keyword.operator.note.diagram.mermaid
%%                ^ string.text.note.diagram.mermaid
  A->B: Hello Bob, how are you?
%% <- meta.declaration.message.diagram.mermaid
%% ^^ keyword.operator.message.diagram.mermaid
%%    ^ keyword.operator.message.diagram.mermaid
%%      ^ string.text.message.diagram.mermaid
  loop Healthcheck
%% <- meta.declaration.loop.diagram.mermaid
%% ^ keyword.type.begin.loop.diagram.mermaid
%%     ^ string.text.loop.diagram.mermaid
    B->B: Bob checks himself...
%% <- meta.declaration.message.diagram.mermaid
%%   ^^ keyword.operator.message.diagram.mermaid
%%      ^ keyword.operator.message.diagram.mermaid
%%        ^ string.text.message.diagram.mermaid
  end
%% <- meta.declaration.loop.diagram.mermaid
%% ^ keyword.type.end.loop.diagram.mermaid
  Note over B: Bob whispers when sick
  alt is sick
%% <- meta.declaration.alternative-path.diagram.mermaid
%% ^ keyword.type.begin.alternative-path.diagram.mermaid
%%     ^ string.text.alternative-path.diagram.mermaid
    B-->A: Not so good :(
  else is well
%% ^ keyword.operator.alternative-path.diagram.mermaid
%%     ^ string.text.alternative-path.diagram.mermaid
    B->A: Feeling fresh like a daisy
  end
%% <- meta.declaration.alternative-path.diagram.mermaid
%% ^ keyword.type.end.alternative-path.diagram.mermaid
  opt Extra response
%% <- meta.declaration.optional-path.diagram.mermaid
%% ^ keyword.type.begin.optional-path.diagram.mermaid
%%     ^ string.text.optional-path.diagram.mermaid
    B->A: You, Alice?
  end
%% <- meta.declaration.optional-path.diagram.mermaid
%% ^ keyword.type.end.optional-path.diagram.mermaid
  Note right of C: Carol is the boss
  C->>A: Get back to work!
%% <- meta.declaration.message.diagram.mermaid
%% ^^^ keyword.operator.message.diagram.mermaid
%%     ^ keyword.operator.message.diagram.mermaid
%%       ^ string.text.message.diagram.mermaid
  loop Every hour
    A->>B: Request 1
    activate B
%% <- meta.declaration.activation.diagram.mermaid
%%  ^ keyword.type.activation.diagram.mermaid
    A-x+B: Request 2
%% <- meta.declaration.message.diagram.mermaid
%%   ^^^ keyword.operator.message.diagram.mermaid
%%       ^ keyword.operator.message.diagram.mermaid
%%         ^ string.text.message.diagram.mermaid
    B--x-A: Response 2
%% <- meta.declaration.message.diagram.mermaid
%%   ^^^^ keyword.operator.message.diagram.mermaid
%%        ^ keyword.operator.message.diagram.mermaid
%%          ^ string.text.message.diagram.mermaid
    B-->>A: Response 1
%% <- meta.declaration.message.diagram.mermaid
%%   ^^^^ keyword.operator.message.diagram.mermaid
%%        ^ keyword.operator.message.diagram.mermaid
%%          ^ string.text.message.diagram.mermaid
    deactivate B
%% <- meta.declaration.activation.diagram.mermaid
%%  ^ keyword.type.activation.diagram.mermaid
  end
